# Generated by Django 5.0.4 on 2024-04-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='video',
            field=models.FileField(upload_to='media/videos'),
        ),
    ]
