# Generated by Django 5.0.4 on 2024-04-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('thumbnail', models.ImageField(upload_to='static/thumbnails/')),
                ('video_file', models.FileField(upload_to='static/videos/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
