# Generated by Django 5.0.3 on 2024-05-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddy', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
